version: "3"

services:
    app:
        build:
            context: .
        ports:
            - "8000:8000"
        volumes:
            - ./app:/app
        command: >
            sh -c "python manage.py wait_for_db &&
                   python manage.py migrate &&
                   python manage.py runserver 0.0.0.0:8000"
        environment:
            - DB_HOST=db
            - DB_NAME=arianadb
            - DB_USER=ariana
            - DB_PASS=arianateam
        depends_on:
            - db

    db:
        image: postgres:12.3
        environment:
            - POSTGRES_DB=arianadb
            - POSTGRES_USER=ariana
            - POSTGRES_PASSWORD=arianateam
        volumes:
            - ./postgres-data:/var/lib/postgresql/data