# Generated by Django 3.0.6 on 2020-05-24 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='ایمیل')),
                ('phone_number', models.CharField(blank=True, max_length=15, verbose_name='شماره تلفن همراه')),
                ('first_name', models.CharField(blank=True, max_length=55, verbose_name='نام')),
                ('last_name', models.CharField(blank=True, max_length=55, verbose_name='نام خانوادگی')),
                ('credit', models.IntegerField(null=True, verbose_name='اعتبار')),
                ('points', models.IntegerField(null=True, verbose_name='امتیاز')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال است')),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
