# Generated by Django 3.0.6 on 2020-05-29 09:19

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(null=True, upload_to=users.models.profile_image_file_path, verbose_name='تصویر کاربری'),
        ),
    ]
