# Generated by Django 3.0.6 on 2020-05-31 09:08

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام')),
                ('image', models.ImageField(null=True, upload_to=core.models.certificate_image_file_path)),
                ('thumbnail', models.ImageField(null=True, upload_to=core.models.certificate_image_file_path)),
                ('grade', models.IntegerField(null=True, verbose_name='نمره')),
                ('minimum_grade', models.IntegerField(verbose_name='حداقل نمره')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
