# Generated by Django 3.0.6 on 2020-06-13 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200613_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='slug',
            field=models.SlugField(),
        ),
    ]
